# Generated by Django 4.2.3 on 2023-07-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categories_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
