# Generated by Django 4.2.3 on 2023-07-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listings_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
