# Generated by Django 4.2.3 on 2023-07-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listings_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
